[package]
name = "location"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]

[dependencies]
yew = { git = "https://github.com/DenisKolodin/yew", branch = "master" }
yew_patterns = { path = "../.."}
stdweb = "0.4.8"
